/localization/dvl/dvl_odometry_component:
  ros__parameters:
    offset_x: 0.4375
    offset_y: 0.0
    offset_z: 0.0


/localization/localization_component:
  ros__parameters:
    coord_system_id: 3
    depth: false # If true, depth enable
    imu: true # If true, imu enable
    dvl: true # If true, dvl enable. Required imu is true.
    gnss: true # If true, calculate global possition
