/**:
  ros__parameters:
    #path_csv: "assets/kobe/gate_path.csv"
    path_csv: "assets/kobe/sample.csv"

    timeout_ms: 30000
    look_ahead_scale: 1.0

    reach_tolerance:
      x: 0.1
      y: 0.1
      z: 0.1
      roll: 10.0
      yaw: 5.0
    waypoint_tolerance:
      x: 0.2
      y: 0.2
      z: 0.2
      roll: 10.0
      yaw: 5.0
