/**:
  ros__parameters:
    path_csv: "assets/kobe/gate_path.csv"
    look_ahead_scale: 1.0

    reach_tolerance:
      x: 0.1
      y: 0.1
      z: 0.1
      roll: 1.0
      yaw: 0.5
    waypoint_tolerance:
      x: 0.2
      y: 0.2
      z: 0.2
      roll: 2.0
      yaw: 5.0
