/**:
  ros__parameters:
    details: true
    checks:
      - "logic_distro_rp2040_driver::SystemSwitchSubscriberCheck"
      - "logic_distro_rp2040_driver::PowerStateTopicStatusCheck"
      - "system_check::PassCheck"
      # - "system_check::FailCheck"
      # - "system_check::TopicStatusCheck"
      - "system_check::ServiceServerCheck"
      - "system_check::ActionServerCheck"

    battery:
      topic_name: "/battery"
      timeout_ms: 1000

    logic_distro_rp2040_driver:
      power_state_topic_status_check:
        topic_name: /logic_distro_rp2040_driver/power_state
        timeout_ms: 4000
        expected: 1

      system_switch_subscriber_check:
        topic_name: /logic_distro_rp2040_driver/system_switch
        timeout_ms: 4000
        expected: 1
